// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohyqjcwozpmrpaydiwhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oeXFqY3dvenBtcnBheWRpd2htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzk4NDcsImV4cCI6MjA2NDcxNTg0N30.dbfsul6aQj-zUcJnIMyzoGuhZyXNet8s7AcdmnSsbbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);